### ISSUE TITLE
Battle music

### ISSUE THREAD

**Issue by halfalahi** [Ap0gee/Ashita-MountMuzzle#1]
im trying to switch the battle music to Ceizak_Battlegrounds battle music "  Knotted Root fight "

i have no idea how to do it would you please send me the command to do it?

thank you

**Comment by Sjshovan** [comment]
This is not an issue, this is a question, and I believe it is not related to this addon. Please send me an email for any questions and please confirm the addon you are asking about. **Sjshovan@Gmail.com**
